# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EtapaRecurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edital', models.CharField(max_length=200)),
                ('tipoProva', models.CharField(max_length=200)),
                ('dataAbertura', models.DateTimeField(verbose_name='Data Abertura')),
                ('dataFechamento', models.DateTimeField(verbose_name='Data Fechamento')),
            ],
        ),
    ]
