# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-18 20:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemarecursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('questao', models.IntegerField(default=0)),
                ('textoRecurso', models.TextField()),
                ('timestamp', models.DateTimeField(verbose_name='Data de Subsmissao')),
                ('etapaRecurso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemarecursos.EtapaRecurso')),
            ],
        ),
    ]
