# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-19 20:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistemarecursos', '0002_recurso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('inscricao', models.CharField(max_length=10)),
                ('cpf', models.CharField(max_length=14)),
                ('cargo_area', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='recurso',
            name='questao',
            field=models.CharField(max_length=2),
        ),
        migrations.AddField(
            model_name='candidato',
            name='recurso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistemarecursos.Recurso'),
        ),
    ]
