# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 09:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemarecursos', '0004_auto_20180121_1412'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidato',
            old_name='cpf',
            new_name='rg',
        ),
    ]
