# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 02:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sistemarecursos', '0007_auto_20180126_1117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurso',
            name='textoRecurso',
            field=ckeditor.fields.RichTextField(max_length=5000),
        ),
    ]
