# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-27 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistemarecursos', '0008_auto_20180127_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurso',
            name='solicitacao',
            field=models.CharField(default='anular', max_length=40),
            preserve_default=False,
        ),
    ]
